apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-1g
  namespace : demo
  labels:
    storetype: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.117.186.63
    path: "/data/kube-pv"
