apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: http-svc-ingress
  namespace: kube-system
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ingress.myrepo.com
    http:
      paths:
      - path: /http-svc
        backend:
          serviceName: http-svc
          servicePort: 80
