apiVersion: v1
kind: Service
metadata:
  name: http-svc
  labels:
    app: http-svc
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    # This port needs to be available on all nodes in the cluster
    nodePort: 30301
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: http-svc
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: http-svc
  namespace: kube-system
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: http-svc
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: http-svc
        image: harbor.epei360.com/library/echoserver:1.5
        ports:
        - containerPort: 8080
        env:
           - name: NODE_NAME
             valueFrom:
               fieldRef:
                 fieldPath: spec.nodeName
           - name: POD_NAME
             valueFrom:
               fieldRef:
                 fieldPath: metadata.name
           - name: POD_NAMESPACE
             valueFrom:
               fieldRef:
                 fieldPath: metadata.namespace
           - name: POD_IP
             valueFrom:
               fieldRef:
                 fieldPath: status.podIP
