apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-3g-03
  namespace : default
  labels:
    storetype: nfs
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.117.186.63
    path: "/data/kube-pv/zookeeper/node3"
